In [93]:
!pip install numpy

In [6]:
import numpy as np

In [8]:
list = [1,2,3,4,5]
arr=np.array(list)

In [10]:
arr

array([1, 2, 3, 4, 5])

In [12]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
from numpy import random

In [20]:
y = random.randint(50,size=(3,3))
print(y)

[[31  3 21]
 [21 37 32]
 [29  4  8]]


In [22]:
zeros_array = np.zeros((2, 3))
print("Zeros Array:\n", zeros_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

prime_numbers = [num for num in range(1, 100) if is_prime(num)]

prime_array = np.array(prime_numbers)

print(prime_array)

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


In [26]:
def check_even_odd(number):
    if number % 2 == 0:
        return "Even"
    else:
        return "Odd"

num = int(input("Enter a number: "))
result = check_even_odd(num)
print(f"The number {num} is {result}.")

Enter a number:  45


The number 45 is Odd.


In [42]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

num = 5
print(f"The factorial of {num} is:", factorial(num))

The factorial of 5 is: 120


In [30]:
num = int(input("Enter a number: "))
if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

Enter a number:  -55


Negative


In [32]:
def calculator(a, b, operation):
    if operation == 'add':
        return a + b
    elif operation == 'subtract':
        return a - b
    elif operation == 'multiply':
        return a * b
    elif operation == 'divide':
        return a / b
    else:
        return "Invalid operation"

In [36]:
num1 = 70
num2 = 5
operation = 'multiply'
result = calculator(num1 , num2, operation)
print(result)

350


In [38]:
def vowels(text):
    vowels = "aeiouAEIOU"
    count = 0
    for char in text:
        if char in vowels:
            count += 1
    return count

In [40]:
text = "You are welcomed, At our Office"
total_vowels = vowels(text)
print(f"Number of vowels :" , total_vowels)

Number of vowels : 13


In [48]:
data = np.array([1, 2, 3, 4, 5,8, 10, 12])
mean = np.mean(data)
print(mean)

5.625


In [50]:
median = np.median(data)
print(median)

4.5


In [52]:
mode = np.mode(data)
print(mode)

AttributeError: module 'numpy' has no attribute 'mode'

In [54]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
product = np.dot(matrix1, matrix2)

In [56]:
print(product)

[[19 22]
 [43 50]]


In [58]:
arr = np.array([2, 8, 1, 5, 10, 3, -78, -56, 0])
max_value = np.max(arr)
min_value = np.min(arr)

In [60]:
print(max_value)
print(min_value)

10
-78


In [108]:
class Rectangle:
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def area(self):
        return self.width * self.height

rec_area = Rectangle(5, 10)
print("Area of the rectangle:", rec_area.area())

Area of the rectangle: 50


In [114]:
class Animal:
    def __init__(self, name):
        self.name = name

    def sound(self):
        pass

class Dog(Animal):
    def sound(self):
        return "Barks!"

dog = Dog("Tommy")
print(f"{dog.name} {dog.sound()}")

Tommy Barks!


In [120]:
import time

def countdown(seconds):
    while seconds > 0:
        print(f"{seconds} seconds remaining")
        time.sleep(1)
        seconds -= 1
    print("Time's up!")
countdown(5)

5 seconds remaining
4 seconds remaining
3 seconds remaining
2 seconds remaining
1 seconds remaining
Time's up!


In [126]:
def sum_even_numbers(numbers):
    return sum(num for num in numbers if num % 2 == 0)

numbers = [1, 2, 3, 4, 5, 6]
result = sum_even_numbers(numbers)
print(result)

12


In [128]:
def simple_interest(principal, rate, time):
    return (principal * rate * time) / 100

print(simple_interest(10000, 7, 2)) 

1400.0
